[package]
name = "kvstore"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kvstore"
doc = false

[dependencies]
clap = { version = "3.0.0", features = ["derive"] }
hex = "0.4.3"
minicbor = { version = "0.12.0", features = ["derive", "std"] }
many = { git = "https://github.com/l-1-labs/many-rs.git", rev = "454d5375f00d56e2718f1a3ba275082901298653" }
many-client = { git = "https://github.com/l-1-labs/many-rs.git", rev = "454d5375f00d56e2718f1a3ba275082901298653" }
many-kvstore = { path = "../many-kvstore" }
tracing = "0.1.29"
tracing-subscriber = "0.3.3"
tokio = { version = "1.12.0", features = [ "full" ] }
