[package]
name = "kvstore"
version = "0.1.0"
edition = "2021"
authors = ["The Lifted Initiative"]
license = "Apache-2.0"
description = ""
readme = "README.md"
homepage = "https://liftedinit.org"
repository = "https://github.com/the-lifted-initiative/many-framework"
keywords = ["cli", "web3", "blockchain", "tendermint", "proto", "crypto", "the-lifted-initiative"]
categories = ["command-line-utilities"]

[[bin]]
name = "kvstore"
doc = false

[dependencies]
clap = { version = "3.0.0", features = ["derive"] }
hex = "0.4.3"
minicbor = { version = "0.12.0", features = ["derive", "std"] }
many = { git = "https://github.com/the-lifted-initiative/many-rs.git", rev = "07f11f4d3b2d640998f7f5b6c980e7d02f395e63" }
many-client = { git = "https://github.com/the-lifted-initiative/many-rs.git", rev = "07f11f4d3b2d640998f7f5b6c980e7d02f395e63" }
many-kvstore = { path = "../many-kvstore" }
tracing = "0.1.29"
tracing-subscriber = "0.3.3"
tokio = { version = "1.12.0", features = [ "full" ] }
