[workspace]

members = [
    "src/http_proxy",
    "src/idstore-export",
    "src/ledger",
    "src/kvstore",
    "src/many-abci",
    "src/many-kvstore",
    "src/many-ledger",
]

[profile.release]
strip = true  # Strip debug info from release build
lto = true  # Perform "fat" LTO
codegen-units = 1 # Improve the performance of the generated code at the cost of compile time
incremental = false

[profile.dev]
incremental = false

# [patch."https://github.com/liftedinit/many-rs.git"]
# many = { path = "../many-rs/src/many" }
# many-cli = { path = "../many-rs/src/many-cli" }
# many-client = { path = "../many-rs/src/many-client" }
# many-macros = { path = "../many-rs/src/many-macros" }

[patch.crates-io]
ciborium = { git = "https://github.com/enarx/ciborium", rev = "2ca375e6b33d1ade5a5798792278b35a807b748e" }
ciborium-io = { git = "https://github.com/enarx/ciborium", rev = "2ca375e6b33d1ade5a5798792278b35a807b748e" }
