[workspace]

members = [
    "src/http_proxy",
    "src/ledger",
    "src/kvstore",
    "src/many-abci",
    "src/many-kvstore",
    "src/many-ledger",
]

# [patch."https://github.com/the-lifted-initiative/many-rs.git"]
# many = { path = "../many-rs/src/many" }
# many-cli = { path = "../many-rs/src/many-cli" }
# many-client = { path = "../many-rs/src/many-client" }
# many-macros = { path = "../many-rs/src/many-macros" }
