[workspace]

members = [
    "src/http_proxy",
    "src/idstore-export",
    "src/ledger",
    "src/kvstore",
    "src/many-abci",
    "src/many-kvstore",
    "src/many-ledger",
]

[profile.release]
strip = true  # Strip debug info from release build
lto = true  # Perform "fat" LTO
codegen-units = 1 # Improve the performance of the generated code at the cost of compile time
incremental = false

[profile.dev]
incremental = false

[patch."https://github.com/liftedinit/many-rs.git"]
many = { git = "https://github.com/fmorency/many-rs.git", branch = "fmorency/fix-async-return" }
many-client = { git = "https://github.com/fmorency/many-rs.git", branch = "fmorency/fix-async-return" }
many-client-macros = { git = "https://github.com/fmorency/many-rs.git", branch = "fmorency/fix-async-return" }
many-error = { git = "https://github.com/fmorency/many-rs.git", branch = "fmorency/fix-async-return" }
many-identity = { git = "https://github.com/fmorency/many-rs.git", branch = "fmorency/fix-async-return" }
many-identity-dsa = { git = "https://github.com/fmorency/many-rs.git", branch = "fmorency/fix-async-return" }
many-identity-hsm = { git = "https://github.com/fmorency/many-rs.git", branch = "fmorency/fix-async-return" }
many-identity-webauthn = { git = "https://github.com/fmorency/many-rs.git", branch = "fmorency/fix-async-return" }
many-macros = { git = "https://github.com/fmorency/many-rs.git", branch = "fmorency/fix-async-return" }
many-mock = { git = "https://github.com/fmorency/many-rs.git", branch = "fmorency/fix-async-return" }
many-modules = { git = "https://github.com/fmorency/many-rs.git", branch = "fmorency/fix-async-return" }
many-protocol = { git = "https://github.com/fmorency/many-rs.git", branch = "fmorency/fix-async-return" }
many-server = { git = "https://github.com/fmorency/many-rs.git", branch = "fmorency/fix-async-return" }
many-types = { git = "https://github.com/fmorency/many-rs.git", branch = "fmorency/fix-async-return" }

[patch.crates-io]
ciborium = { git = "https://github.com/enarx/ciborium", rev = "2ca375e6b33d1ade5a5798792278b35a807b748e" }
ciborium-io = { git = "https://github.com/enarx/ciborium", rev = "2ca375e6b33d1ade5a5798792278b35a807b748e" }
