[package]
name = "http_proxy"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "http_proxy"
doc = false

[dependencies]
clap = { version = "3.0.0", features = ["derive"] }
hex = "0.4.3"
minicbor = { version = "0.12.0", features = ["derive", "std"] }
many = { git = "https://github.com/the-lifted-initiative/many-rs.git", rev = "622bf223cb9581793c70a9e7886729b4bb75f9f9" }
many-client = { git = "https://github.com/the-lifted-initiative/many-rs.git", rev = "622bf223cb9581793c70a9e7886729b4bb75f9f9" }
many-kvstore = { path = "../many-kvstore" }
new_mime_guess = "4.0.0"
tiny_http = "0.9.0"
tracing = "0.1.29"
tracing-subscriber = "0.3.3"
tokio = { version = "1.12.0", features = [ "full" ] }
