[package]
name = "ledger"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ledger"
doc = false

[dependencies]
clap = { version = "3.0.0", features = ["derive"] }
crc-any = "2.4.0"
derive_builder = "0.10.2"
fmerk = { git = "https://github.com/hansl/fmerk" }
hex = "0.4.3"
lazy_static = "1.4.0"
minicbor = { version = "0.12.0", features = ["derive", "std"] }
num-bigint = "0.4.3"
many = { git = "https://github.com/l-1-labs/many-rs.git", rev = "feb5837edbe8c8d8b9323b4b081b69cc88f782bb" }
many-client = { git = "https://github.com/l-1-labs/many-rs.git", rev = "feb5837edbe8c8d8b9323b4b081b69cc88f782bb" }
regex = "1.5.4"
ring = "0.17.0-alpha.10"
tracing = "0.1.29"
tracing-subscriber = "0.3.3"
tokio = { version = "1.12.0", features = [ "full" ] }
