[package]
name = "ledger"
version = "0.1.0"
edition = "2021"
authors = ["The Lifted Initiative"]
license = "Apache-2.0"
description = ""
readme = "README.md"
homepage = "https://liftedinit.org"
repository = "https://github.com/liftedinit/many-framework"
keywords = ["cli", "web3", "blockchain", "tendermint", "proto", "crypto", "liftedinit"]
categories = ["command-line-utilities"]

[[bin]]
name = "ledger"
doc = false

[dependencies]
clap = { version = "3.0.0", features = ["derive"] }
crc-any = "2.4.0"
derive_builder = "0.10.2"
merk = { git = "https://github.com/liftedinit/merk.git", rev = "253678fe9fdb02bd4ade04790ad8f41801c73d95" }
hex = "0.4.3"
humantime = "2.1.0"
indicatif = "0.16.2"
lazy_static = "1.4.0"
minicbor = { version = "0.12.0", features = ["derive", "std"] }
num-bigint = "0.4.3"
many = { git = "https://github.com/liftedinit/many-rs.git", rev = "f19fbb86f2ffe61bb728e29921bc687cb66b4199" }
many-client = { git = "https://github.com/liftedinit/many-rs.git", rev = "f19fbb86f2ffe61bb728e29921bc687cb66b4199" }
regex = "1.5.4"
ring = "0.17.0-alpha.10"
rpassword = "6.0"
tracing = "0.1.29"
tracing-subscriber = "0.3"
tracing-syslog = { git = "https://github.com/max-heller/tracing-syslog.git", rev = "6ff222831d7a78f1068d4c8af94dea215b07f114" }
tokio = { version = "1.12.0", features = [ "full" ] }
