[package]
name = "ledger"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ledger"
doc = false

[dependencies]
clap = { version = "3.0.0", features = ["derive"] }
crc-any = "2.4.0"
derive_builder = "0.10.2"
fmerk = { git = "https://github.com/hansl/fmerk" }
hex = "0.4.3"
lazy_static = "1.4.0"
minicbor = { version = "0.12.0", features = ["derive", "std"] }
num-bigint = "0.4.3"
many = { git = "https://github.com/the-lifted-initiative/many-rs.git", rev = "622bf223cb9581793c70a9e7886729b4bb75f9f9" }
many-client = { git = "https://github.com/the-lifted-initiative/many-rs.git", rev = "622bf223cb9581793c70a9e7886729b4bb75f9f9" }
regex = "1.5.4"
ring = "0.17.0-alpha.10"
rpassword = "6.0"
tracing = "0.1.29"
tracing-subscriber = "0.3.3"
tokio = { version = "1.12.0", features = [ "full" ] }
