[package]
name = "ledger"
version = "0.1.0"
edition = "2021"
authors = ["The Lifted Initiative"]
license = "Apache-2.0"
description = ""
readme = "README.md"
homepage = "https://liftedinit.org"
repository = "https://github.com/liftedinit/many-framework"
keywords = ["cli", "web3", "blockchain", "tendermint", "proto", "crypto", "liftedinit"]
categories = ["command-line-utilities"]

[[bin]]
name = "ledger"
doc = false

[dependencies]
clap = { version = "3.0.0", features = ["derive"] }
crc-any = "2.4.0"
hex = "0.4.3"
humantime = "2.1.0"
indicatif = "0.16.2"
lazy_static = "1.4.0"
minicbor = { version = "0.18.0", features = ["derive", "std"] }
num-bigint = "0.4.3"
many-client = { git = "https://github.com/liftedinit/many-rs.git", rev = "72b978ff9464207b5517dbe2fb3b01b5b56855ff" }
many-error = { git = "https://github.com/liftedinit/many-rs.git", rev = "72b978ff9464207b5517dbe2fb3b01b5b56855ff" }
many-identity = { git = "https://github.com/liftedinit/many-rs.git", rev = "72b978ff9464207b5517dbe2fb3b01b5b56855ff" }
many-modules = { git = "https://github.com/liftedinit/many-rs.git", rev = "72b978ff9464207b5517dbe2fb3b01b5b56855ff" }
many-protocol = { git = "https://github.com/liftedinit/many-rs.git", rev = "72b978ff9464207b5517dbe2fb3b01b5b56855ff" }
many-types = { git = "https://github.com/liftedinit/many-rs.git", rev = "72b978ff9464207b5517dbe2fb3b01b5b56855ff" }
regex = "1.5.4"
ring = "0.17.0-alpha.10"
rpassword = "6.0"
tracing = "0.1.29"
tracing-subscriber = "0.3"
tracing-syslog = { git = "https://github.com/max-heller/tracing-syslog.git", rev = "6ff222831d7a78f1068d4c8af94dea215b07f114" }
tokio = { version = "1.12.0", features = [ "full" ] }
