[package]
name = "many-kvstore"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "many-kvstore"
doc = false

[dependencies]
async-trait = "0.1.51"
clap = { version = "3.0.0", features = ["derive"] }
fmerk = { git = "https://github.com/hansl/fmerk" }
hex = "0.4.3"
itertools = "0.10.3"
lazy_static = "1.4.0"
num-bigint = "0.4.3"
minicbor = { version = "0.12.0", features = ["derive", "std"] }
many = { git = "https://github.com/the-lifted-initiative/many-rs.git", rev = "622bf223cb9581793c70a9e7886729b4bb75f9f9", features = ["pem"] }
many-abci = { path = "../many-abci" }
serde = "1.0.130"
serde_json = "1.0.72"
sha3 = "0.9.1"
simple_asn1 = "0.5.4"
tracing = "0.1.28"
tracing-subscriber = "0.2.24"
