[package]
name = "ledger-db"
version = "0.1.0"
edition = "2021"
authors = ["The Lifted Initiative"]
license = "Apache-2.0"
description = ""
readme = "README.md"
homepage = "https://liftedinit.org"
repository = "https://github.com/liftedinit/many-framework"
keywords = ["cli", "web3", "blockchain", "tendermint", "proto", "crypto", "liftedinit"]
categories = ["command-line-utilities"]

[[bin]]
name = "ledger-db"
doc = false

[dependencies]
clap = { version = "3.0.0", features = ["derive"] }
hex = "0.4.3"
merk = { git = "https://github.com/liftedinit/merk.git", rev = "da0b660abbfd58abd4a942773f205d2c079f3b27" }
many-modules = { git = "https://github.com/liftedinit/many-rs.git", rev = "b649ee3709197dae3fdff883146d9ea6a13551c7" }
many-types = { git = "https://github.com/liftedinit/many-rs.git", rev = "b649ee3709197dae3fdff883146d9ea6a13551c7" }
minicbor = "0.18.0"
