[package]
name = "ledger-db"
version = "0.1.0"
edition = "2021"
authors = ["The Lifted Initiative"]
license = "Apache-2.0"
description = ""
readme = "README.md"
homepage = "https://liftedinit.org"
repository = "https://github.com/liftedinit/many-framework"
keywords = ["cli", "web3", "blockchain", "tendermint", "proto", "crypto", "liftedinit"]
categories = ["command-line-utilities"]

[[bin]]
name = "ledger-db"
doc = false

[dependencies]
clap = { version = "3.0.0", features = ["derive"] }
hex = "0.4.3"
merk = { git = "https://github.com/liftedinit/merk.git", rev = "3d509c8efd3a68d85a5769f7fff300e10290d137" }
many-modules = { git = "https://github.com/liftedinit/many-rs.git", rev = "0db81ac956bc68c5c43f3f16ede9435ecceb4801" }
many-types = { git = "https://github.com/liftedinit/many-rs.git", rev = "0db81ac956bc68c5c43f3f16ede9435ecceb4801" }
minicbor = "0.18.0"
