[package]
name = "many-ledger"
version = "0.1.0"
edition = "2021"
authors = ["The Lifted Initiative"]
license = "Apache-2.0"
description = ""
readme = "README.md"
homepage = "https://liftedinit.org"
repository = "https://github.com/liftedinit/many-framework"
keywords = ["cli", "web3", "blockchain", "tendermint", "proto", "crypto", "liftedinit"]
categories = ["command-line-utilities"]

[[bin]]
name = "many-ledger"
doc = false

[dependencies]
async-trait = "0.1.51"
bip39-dict = "0.1"
clap = { version = "3.0.0", features = ["derive"] }
coset = "0.3"
fixed = "1.11.0"
fmerk = { git = "https://github.com/hansl/fmerk" }
hex = "0.4.3"
itertools = "0.10.3"
lazy_static = "1.4.0"
num-bigint = "0.4.3"
num-traits = "0.2.14"
minicbor = { version = "0.12.0", features = ["derive", "std"] }
many = { git = "https://github.com/liftedinit/many-rs.git", rev = "c80f6314957bc0d7b084c883367bc012b5d473f7", features = ["pem", "raw"] }
many-abci = { path = "../many-abci" }
many-kvstore = { path = "../many-kvstore" }
rand = "0.8"
serde = "1.0.130"
serde_json = "1.0.72"
sha3 = "0.9.1"
signal-hook = "0.3.13"
simple_asn1 = "0.5.4"
tracing = "0.1.28"
tracing-subscriber = "0.2.24"
typenum = "1.15.0"

[dev-dependencies]
many = { git = "https://github.com/liftedinit/many-rs.git", rev = "c80f6314957bc0d7b084c883367bc012b5d473f7", features = ["testing"] }
many-client = { git = "https://github.com/liftedinit/many-rs.git", rev = "c80f6314957bc0d7b084c883367bc012b5d473f7" }
tempfile = "3.3.0"

[features]
balance_testing=[]
