[package]
name = "many-ledger"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "many-ledger"
doc = false

[dependencies]
async-trait = "0.1.51"
bip39-dict = "0.1"
clap = { version = "3.0.0", features = ["derive"] }
coset = "0.3"
fixed = "1.11.0"
fmerk = { git = "https://github.com/hansl/fmerk" }
hex = "0.4.3"
itertools = "0.10.3"
lazy_static = "1.4.0"
num-bigint = "0.4.3"
num-traits = "0.2.14"
minicbor = { version = "0.12.0", features = ["derive", "std"] }
many = { git = "https://github.com/fmorency/many-rs.git", rev = "ff68bdd619ee06fedaf315968d05110981cd64d5", features = ["pem", "raw"] }
many-abci = { path = "../many-abci" }
many-kvstore = { path = "../many-kvstore" }
rand = "0.8"
retry = "1.3"
serde = "1.0.130"
serde_json = "1.0.72"
sha3 = "0.9.1"
signal-hook = "0.3.13"
simple_asn1 = "0.5.4"
tracing = "0.1.28"
tracing-subscriber = "0.2.24"
typenum = "1.15.0"

[dev-dependencies]
many = { git = "https://github.com/fmorency/many-rs.git", rev = "ff68bdd619ee06fedaf315968d05110981cd64d5", features = ["testing"]}
many-client = { git = "https://github.com/fmorency/many-rs.git", rev = "ff68bdd619ee06fedaf315968d05110981cd64d5" }
tempfile = "3.3.0"

