name: Create release

on:
  release:
    types: [created]

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Create release archive
      run: find target/release/ -maxdepth 1 -executable -type f -print0 | tar czvf many-framework.tar.gz --null -T -
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_name: fmorency/many-framework
        # A personal access token for the GitHub repository in which the release will be created and edited.
        # It is recommended to create the access token with the following scopes: `repo, user, admin:repo_hook`.
        repo_token: ${{ secrets.RELEASE_TOKEN }}
        file: many-framework.tar.gz
        asset_name: many-framework
        tag: ${{ github.ref }}
        overwrite: true
        body: "many-framework pre-alpha"